### ISSUE TITLE
Add Numpad Board: PyKey18

### ISSUE THREAD

**Issue by jpconstantineau** [jpconstantineau/PyKey60#4]
* RP2040 on board
* TRRS to connect to PyKey87
* OLED
* Rotary Encoder  - 1 key
* Standard Numpad layout
* Per-key RGB
* Hot Swap Sockets
* Same height as PyKey87
* Feet positions: same distance from bottom
* Standard numpad layout as per http://www.keyboard-layout-editor.com/  17 keys
* Use GPIO 27/28 for EncA/B

**Comment by nitronarcosis** [comment]
I'm a little wary of running speaker in parallel to reset but that's probably not a big deal because any induced current will drive it high, not low.
I also don't see any decoupling capacitors on the LEDs.
Is there ESD protection? I'm not seeing that either.

**Comment by jpconstantineau** [comment]
Added a grounded line between most of the Reset and Speaker lines
Added caps
Added ESD protection.
